PLC_CREATED = "PLC_CREATED"
PLC_UPDATED = "PLC_UPDATED"
PLC_DISABLED = "PLC_DISABLED"

TEMPLATE_CREATED = "TEMPLATE_CREATED"
TEMPLATE_UPDATED = "TEMPLATE_UPDATED"
TEMPLATE_DISABLED = "TEMPLATE_DISABLED"

PARAMETER_ADDED = "PARAMETER_ADDED"
PARAMETER_UPDATED = "PARAMETER_UPDATED"
PARAMETER_DISABLED = "PARAMETER_DISABLED"

PHASE_CONTROL_CREATED = "PHASE_CONTROL_CREATED"
PHASE_CONTROL_UPDATED = "PHASE_CONTROL_UPDATED"

PHASE_OPTION_ADDED = "PHASE_OPTION_ADDED"
PHASE_OPTION_UPDATED = "PHASE_OPTION_UPDATED"

PHASE_MAPPING_CREATED = "PHASE_MAPPING_CREATED"
PHASE_MAPPING_UPDATED = "PHASE_MAPPING_UPDATED"

MACHINE_CREATED = "MACHINE_CREATED"
MACHINE_UPDATED = "MACHINE_UPDATED"

STAGE_CREATED = "STAGE_CREATED"
STAGE_UPDATED = "STAGE_UPDATED"

TBM_FAMILY_CREATED = "TBM_FAMILY_CREATED"
TBM_FAMILY_UPDATED = "TBM_FAMILY_UPDATED"