"""Build the production CRS stylesheet from the ordered CSS module manifest."""

from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CSS_ROOT = PROJECT_ROOT / "flask_app" / "static" / "css"
MANIFEST_PATH = CSS_ROOT / "main.css"
OUTPUT_PATH = CSS_ROOT / "crs.bundle.css"
IMPORT_PATTERN = re.compile(r'@import\s+url\(["\']?([^"\')?]+)')


def module_paths() -> list[Path]:
    source = MANIFEST_PATH.read_text(encoding="utf-8")
    paths = []
    for import_path in IMPORT_PATTERN.findall(source):
        clean_path = import_path.split("?", 1)[0]
        path = (CSS_ROOT / clean_path).resolve()
        if CSS_ROOT.resolve() not in path.parents:
            raise ValueError(f"CSS import leaves the static CSS directory: {import_path}")
        if not path.is_file():
            raise FileNotFoundError(f"CSS module does not exist: {path}")
        paths.append(path)
    if not paths:
        raise ValueError("No CSS modules were found in main.css")
    return paths


def render_bundle() -> str:
    sections = []
    paths = module_paths()
    digest = hashlib.sha256()
    for path in paths:
        content = path.read_text(encoding="utf-8").strip()
        digest.update(path.name.encode("utf-8"))
        digest.update(content.encode("utf-8"))
        relative = path.relative_to(CSS_ROOT).as_posix()
        sections.append(f"/* Source: {relative} */\n{content}")
    header = (
        "/* Generated by scripts/build_css_bundle.py. Do not edit directly.\n"
        f" * Modules: {len(paths)} | Source SHA-256: {digest.hexdigest()}\n"
        " */"
    )
    return header + "\n\n" + "\n\n".join(sections) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Build the CRS production CSS bundle.")
    parser.add_argument("--check", action="store_true", help="Fail when the bundle is missing or stale.")
    args = parser.parse_args(argv)
    expected = render_bundle()

    if args.check:
        if not OUTPUT_PATH.is_file():
            print(f"Missing CSS bundle: {OUTPUT_PATH}")
            return 1
        if OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            print("CSS bundle is stale. Run scripts/build_css_bundle.py.")
            return 1
        print(f"CSS bundle is current: {OUTPUT_PATH}")
        return 0

    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    print(f"Built {OUTPUT_PATH} from {len(module_paths())} modules.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
